version: '3.8'

services:
  # PostgreSQL container
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: azbank
      POSTGRES_PASSWORD: bank123
      POSTGRES_DB: azbank_db
    ports:
      - "5432:5432"  # Expose PostgreSQL on port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist data across container restarts

# Volumes for PostgreSQL data persistence
volumes:
  postgres_data:
